name: genai
description: "Generative AI capabilities for flutter applications"
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  better_networking:
    path: ../better_networking
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  nanoid: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  json_serializable: ^6.7.1
  test: ^1.25.2
